server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://106.12.114.58:4000/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: Doyouknow520

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000